language: node_js
node_js:
  - 9
  - 10
  - 11
matrix:
  allow_failures:
    - node_js: 11
os:
  - linux
cache:
  directories:
  - node_modules
install: 
  - npm i
script:
  - cp sample.tasks.json tasks.json
after_script:
  - npm test