language: node_js
node_js:
  - 10
  - 11
matrix:
  allow_failures:
    - node_js: 11
os:
  - linux
cache:
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: 
  - yarn
script:
  - cp sample.tasks.json tasks.json
after_script:
  - yarn test